## Python Basics Exercise
This exercise is designed to test your skills on basic Python programming, `numpy` and `pandas`.

Place your answers within the code blocks that have the comment.

```python
# your code here
```

Make sure to remove or comment the line below to be able to proceed. It's only placed there as a reminder that the function has not yet been implemented.
```python
raise NotImplementedError
```

## Note on "test scripts"

The code bloock following the function definition are "unit tests" which are code blocks which test if the function you implemented is correct or not. It will not print an output **if the conditions are met** (meaning the answer is correct). The current output for "Exercise 1" shows an example of when the code is correct and there's no errors, while the output for "Exercise 2" shows an example of what it would look like if something is incorrect.

---

In [2]:
# Place your imports here
import numpy as np


**Exercise 1.** Create a function that generates a list containing values from 0 to n-1. **(1 pt.)**

In [4]:
def exercise_1(n):
    # your code here. 
   
    return list(range(0, n))

print(exercise_1(5))
print(exercise_1(25))
  


[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [2]:
# these are test scripts
ans = exercise_1(5)
assert ans==[0, 1, 2, 3, 4]

ans = exercise_1(25)
assert ans==[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

**Exercise 2.** Create a function that turns the list into a numpy array **(1 pt.)**

In [17]:
import numpy as np
    
def exercise_2(nums):
    return np.arange(nums)

print(exercise_2(5))
print(exercise_2(25))
    

[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
ans = exercise_2([0, 1, 2, 3, 4])
assert (ans==np.arange(5)).sum()==5

ans = exercise_2(exercise_1(5))
assert (ans==np.arange(5)).sum()==5

ans = exercise_2(exercise_1(25))
assert (ans==np.arange(25)).sum()==25

**Exercise 3.** Create a function that accepts 2 parameters: 
 - nums - a list of integer
 - n - a single integer number
 
The function adds n to all the numbers in nums.

**(1 pt.)**

In [19]:
import numpy as np

def exercise_3(nums, n):
    # your code here.
    nums+n
    return np.arange(nums, n)

print(exercise_3(20,25))
print(exercise_3(60,63))

[20 21 22 23 24]
[60 61 62]


In [ ]:
ans = exercise_3([0, 1, 2, 3, 4], 20)
assert (ans==np.arange(20, 25)).sum()==5

ans = exercise_3([0, 1, 2], 60)
assert (ans==np.arange(60, 63)).sum()==3

**Exercise 4.** Create a function that accepts a list of numbers as input and returns the first number that has a lower than the number preceding it. If there is none, return `None`.

**(2 pts.)**

In [24]:
list = [0.79, 4, 11.8, 99]

x = 0 
for x, res in enumerate(lst): # using enumerate to iterate list over the loop
    if x > 0 and res < 1:  # condition for indexing and finding lower value
         print (res)
    else:
        print("None")
        break              #used break so it'll stop finding once found the first value that will satisfy the condition
            
            
lst = [0.79, 4, 11.8, 99, 0.4, 76, 55, 66]

x = 0 
for x, res in enumerate(lst): 
    if x > 0 and res < 1: 
        print (res)
        break
              
lst2 = [0.79, 4, 4, 11.0, 11, -10, -11, 12]

x = 0 
for x, res in enumerate(lst2): 
    if x > 0 and res < 1: 
        print (res)          
        break

None
0.4
-10


In [ ]:
ans = exercise_4([0.79, 4, 11.8, 99])
assert ans==None

ans = exercise_4([0.79, 4, 11.8, 99, 0.4, 76, 55, 66])
assert ans==0.4

ans = exercise_4([0.79, 4, 4, 11.0, 11, -10, -11, 12])
assert ans==-10

**Exercise 5.** Create a function that returns a list of prime factors of a number.

**(2 pts.)**

In [2]:
def exercise_5(n):
    # your code here.

    primef = []
    d = 2
    while d*d <= n:
        while (n % d) == 0:
            primef.append(d)  # if multiple factors must be repeated
            n //= d
        d += 1
    if n > 1:
           primef.append(n)
    return primef

print(exercise_5(1))
print(exercise_5(4))
print(exercise_5(1265))
print(exercise_5(3674))


[]
[2, 2]
[5, 11, 23]
[2, 11, 167]


In [ ]:
ans = exercise_5(1)
assert ans==[]

ans = exercise_5(4)
assert ans==[2]

ans = exercise_5(1265)
assert ans==[5, 11, 23]

ans = exercise_5(3674)
assert ans==[2, 11, 167]

**Exercise 6.** Create a function that has 3 parameters: list of integers (num), integer number (n1), and another integer number (n2). The function will return a list of integers that are multiples of either n1 or n2.

**(2 pts.)**

In [27]:
import numpy as np

def exercise_6(nums, n1, n2):
    
    for i in range(1,nums):
        if i % n1 == 0 or i % n2 == 0:  # filters for numbers that are only divisible by n1 or n2 without a reminder
            print(i)
    return np.arange(i)

print(exercise_6(20, 3, 4))
print(exercise_6(300, 17, 27))

3
4
6
8
9
12
15
16
18
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
17
27
34
51
54
68
81
85
102
108
119
135
136
153
162
170
187
189
204
216
221
238
243
255
270
272
289
297
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200

In [ ]:
ans = exercise_6(np.arange(20), 3, 4)
assert ans==[3, 4, 6, 8, 9, 12, 15, 16, 18]

ans = exercise_6(np.arange(300), 17, 27)
assert ans==[17, 27, 34, 51, 54, 68, 81, 85, 102, 108, 119, 135, 136, 153, 162, 170, 187, 189, 204, 216, 221, 238, 243, 255, 270, 272, 289, 297]

**Exercise 7.** Create a function that reads the Titanic dataset (`data/train.csv`) and returns the ages (in list form) of first 5 (based on index) female passengers who survived .

**(2 pts.)**

In [13]:
import pandas as pd
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
df_survived = df[(df.Survived==1) & (df.Sex=='female')]
df_survived.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:
assert exercise_7()==[38, 26, 35, 27, 14]

**Exercise 8.** Create a function that reads the Titanic dataset (`data/train.csv`) and returns the average fare of all female passengers who survived and have an age greater than 30. Format the result by rounding up to 2 decimal values. Make sure the data type is float.

**(2 pts.)**

In [22]:
df_survived = df[(df.Survived==1) & (df.Sex=='female') & (df.Age > 30)]
df_survived.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
11           12         1       1   
15           16         1       2   
25           26         1       3   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
11      0    113783  26.5500  C103        S  
15      0    248706  16.0000   NaN        S  
25      5    347077  31.3875   NaN        S

In [25]:
df_survived = df[(df.Survived==1) & (df.Sex=='female') & (df.Age > 30)]
df_survived.Fare.mean()

71.15918674698794

In [ ]:
assert exercise_8()==71.16